name: extract_strings
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  analyzer: ^7.0.0
dev_dependencies:
  lints: ^3.0.0
